// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bl

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/z-riley/platform/example/internal/repository"
)

// NewMockSomethingRepository creates a new instance of MockSomethingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSomethingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSomethingRepository {
	mock := &MockSomethingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSomethingRepository is an autogenerated mock type for the SomethingRepository type
type MockSomethingRepository struct {
	mock.Mock
}

type MockSomethingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSomethingRepository) EXPECT() *MockSomethingRepository_Expecter {
	return &MockSomethingRepository_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockSomethingRepository
func (_mock *MockSomethingRepository) Begin(ctx context.Context) (*repository.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *repository.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*repository.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *repository.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSomethingRepository_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockSomethingRepository_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSomethingRepository_Expecter) Begin(ctx interface{}) *MockSomethingRepository_Begin_Call {
	return &MockSomethingRepository_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockSomethingRepository_Begin_Call) Run(run func(ctx context.Context)) *MockSomethingRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSomethingRepository_Begin_Call) Return(tx *repository.Tx, err error) *MockSomethingRepository_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockSomethingRepository_Begin_Call) RunAndReturn(run func(ctx context.Context) (*repository.Tx, error)) *MockSomethingRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSomething provides a mock function for the type MockSomethingRepository
func (_mock *MockSomethingRepository) UpdateSomething(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSomething")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSomethingRepository_UpdateSomething_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSomething'
type MockSomethingRepository_UpdateSomething_Call struct {
	*mock.Call
}

// UpdateSomething is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSomethingRepository_Expecter) UpdateSomething(ctx interface{}) *MockSomethingRepository_UpdateSomething_Call {
	return &MockSomethingRepository_UpdateSomething_Call{Call: _e.mock.On("UpdateSomething", ctx)}
}

func (_c *MockSomethingRepository_UpdateSomething_Call) Run(run func(ctx context.Context)) *MockSomethingRepository_UpdateSomething_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSomethingRepository_UpdateSomething_Call) Return(err error) *MockSomethingRepository_UpdateSomething_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSomethingRepository_UpdateSomething_Call) RunAndReturn(run func(ctx context.Context) error) *MockSomethingRepository_UpdateSomething_Call {
	_c.Call.Return(run)
	return _c
}
